web/router.ex
defmodule Idol.Router do
  use Idol.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Idol do
    pipe_through :browser

    get "/", PageController, :index
    get "/participants", ParticipantsController, :index
    get "/participants/:name", ParticipantsController, :show

    get "/participants/:person_tag/videos", ParticipantsController, :videos
  end

  # Other scopes may use custom stacks.
  # scope "/api", Idol do
  #   pipe_through :api
  # end
end

lib/idol/data.ex
defmodule Idol.Data do
  @participants_url "http://api.tv4play.se/site/programs/idol"

  def fetch_program_info() do
    HTTPoison.get!(@participants_url)
    |> Map.get(:body)
    |> Poison.decode!()
  end

  def fetch_videos(person_tag, start) do
    "http://api.tv4play.se/play/video_assets.json?tags=#{person_tag}&start=#{start}"
    |> URI.encode()
    |> HTTPoison.get!()
    |> Map.get(:body)
    |> Poison.decode!()
  end
end

lib/idol/endpoint.ex
defmodule Idol.Endpoint do
  use Phoenix.Endpoint, otp_app: :idol

  socket "/socket", Idol.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :idol, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_idol_key",
    signing_salt: "OhTuTklp"

  plug Idol.Router
end

web/controllers/page_controller.ex
defmodule Idol.PageController do
  use Idol.Web, :controller

  def index(conn, _params) do
    data_module = get_data_module()
    info = data_module.fetch_program_info()
    description = info["description"]
    image_url = info["program_image"]
    render conn, "index.html", description: description, image_url: image_url
  end

  def get_data_module() do
    Application.get_env(:idol, :data_module)
  end
end

web/controllers/participants_controller.ex
defmodule Idol.ParticipantsController do
  use Idol.Web, :controller

  def index(conn, _params) do
    data_module = get_data_module()
    program_info = data_module.fetch_program_info()
    participants = extract_participants(program_info)
    render conn, "index.html", participants: participants
  end

  def show(conn, %{"name" => name}) do
    data_module = get_data_module()
    program_info = data_module.fetch_program_info()
    participants = extract_participants(program_info)
    case Enum.find(participants, fn(%{"name" => pname}) -> pname == name end) do
      nil ->
        send_resp(conn, 404, "No participant found by that name")
      participant ->
        render conn, "show.html", participant: participant
    end
  end

  def videos(conn, %{"person_tag" => person_tag} = params) do
    data_module = get_data_module()
    start = Map.get(params, "start", "0")
    |> Integer.parse()
    |> elem(0)
    body = data_module.fetch_videos(person_tag, start)
    videos = Enum.take(body["results"], 5)
    video_count = body["total_hits"]
    render conn, "videos.json", videos: videos, video_count: video_count
  end

  defp extract_participants(program_info) do
    program_info
    |> Map.get("participant_groups")
    |> Enum.find(fn(%{"name" => name}) -> name == "Idoldeltagare 2016" end)
    |> Map.get("participants")
  end

  defp get_data_module() do
    Application.get_env(:idol, :data_module)
  end
end

web/views/error_view.ex
defmodule Idol.ErrorView do
  use Idol.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Idol.LayoutView do
  use Idol.Web, :view
end

web/views/page_view.ex
defmodule Idol.PageView do
  use Idol.Web, :view
end

web/views/participants_view.ex
defmodule Idol.ParticipantsView do
  use Idol.Web, :view

  def render("videos.json", %{videos: videos, video_count: video_count}) do
    %{
      videos: Enum.map(videos, &render_video/1), video_count: video_count
    }
  end

  def parse_description(participant) do
    Map.get(participant, "description")
    |> String.split("\r\n")
    |> Enum.filter(&(&1 != ""))
    |> Enum.map(&String.split(&1, ":", parts: 2))
  end

  def image_url(participant) do
    participant
    |> Map.get("image")
    |> Map.get("url")
  end

  defp render_video(video) do
    Map.take(video, ~w(id title description image))
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Idol">
    <meta name="author" content="Erik Mellegård">

    <title>Idol!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <ul class="nav navbar-nav">
          <li><%= link "Startsida", to: page_path(@conn, :index)%></li>
          <li><%= link "Deltagare", to: participants_path(@conn, :index)%></li>
        </ul>
      </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<img src="<%= @image_url %>" alt="Idol image"/>
<h3><%= @description %></h3>

web/templates/participants/index.html.eex
<%= for participant <- @participants do %>
    <div class="participant">
      <img class="participant-thumb" src='<%= Map.get(participant, "image") |> Map.get("url") %>'/>
      <%= link Map.get(participant, "name"), to: participants_path(@conn, :show, Map.get(participant, "name")), class: "participant-link"%></p>
    </div>
<% end %>

web/templates/participants/show.html.eex
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script>var showParticipant = require('web/static/js/show_participant').ShowParticipant;</script>

<h2><%= Map.get(@participant, "name") %></h2>
<image class="participant-image" src="<%= image_url(@participant)%>"></image>
<div class="participant-description">
  <%= for [key, value] <- parse_description(@participant) do %>
    <p><span class="information-question"><%= key %>:</span> <%= value %></p>
  <% end %>
</div>
<div class="participant-videos"></div>
<button class="btn btn-default" id="loadVideosButton" onclick="showParticipant.loadVideos()">Visa fler videos</button>

<script>showParticipant.init('<%= Map.get(@participant, "person_tag") %>')</script>